### ISSUE TITLE
Events not triggering 

### ISSUE THREAD

**Issue by LucasSouriau** [scheb/two-factor-bundle#211] opened 2019-05-10 12:32 UTC
Hey mate, i'm actually trying to use your bundle in order to make my app more secure. I've followed every steps of your documentation, looked as much as I can in every issues but still. The things is that, after the first authentification step, I can reach the /2fa route with the form. But it seems that events are not triggered, so no auth_code saved in db, not even a mail send...
I've tried different way to force it, but I'm wondering if I've missed a step or a case due to my particular project configuration.

Here my security config
```
security:
  providers:
    medecin_provider:
      entity:
        class: App\Entity\Customer\User
        property: email
        manager_name: 'dynamic'

    medecin_api_provider:
      entity:
        class: App\Entity\Customer\User
        property: token
        manager_name: 'dynamic'

    patient_provider:
      id: App\Security\PatientProvider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_customer:
      pattern: ^/api/customer
      provider: medecin_api_provider
      guard:
        authenticators:
        - App\Security\CustomerUserApiTokenAuthenticator

    medecin:
      # Attention si vous changez le nom faut faire suivre sur le AuthentifcationListener gestion des Log de connexion voir les switch case $key
      # Attention si vous changez le "m" reporter la nouvelle lettre ou format sur la route de déconnexion (routes.yml)
      # Attention pour quitter l'impersonification la route de destination doit être couverte par le même firewall que l'utilisateur impersonifié
      pattern: ^/(login|m|support|retailer|telesphore|admin|easyadmin)
      anonymous: ~
      provider: medecin_provider
      switch_user: true
      guard:
        authenticators:
          - App\Security\Customer\Medecin\MedLoginFormAuthenticator
      form_login:
        login_path: medecin_login
        check_path: medecin_login
        default_target_path: home
        use_referer: true
      logout:
        path: logout_medecin
        target: medecin_login
      context: sharedcontext
      two_factor:
        auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
        check_path: 2fa_login_check  # The route name you have used in the routes.yaml
        provider: medecin_provider
        multi_factor: false
        default_target_path: /
        always_use_default_target_path: true

    patient_area:
      # Attention si vous changez le nom faut faire suivre sur le AuthentifcationListener gestion des Log de connexion voir les switch case $key
      pattern: ^/(code|p) # Attention si vous changez le "p" reporter la nouvelle lettre ou format sur la route de déconnexion (routes.yml)
      anonymous: ~
      provider: patient_provider
      guard:
        authenticators:
        - App\Security\PatientAuthenticator
      form_login:
        login_path: patient_auth_one
        check_path: patient_auth_one
        default_target_path: login_redirect_patient
        use_referer: true
      logout:
        path: logout_patient
        target: patient_auth_one
      context: sharedcontext

    default:
      pattern: ^/
      anonymous: ~
      context: sharedcontext

  access_control:
 
```

Then the bundle configuration i've set
```
# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        # If you're using guard-based authentication, you have to use this one:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken

    # Trusted device feature
    trusted_device:
        enabled: true                 # If the trusted device feature should be enabled
        lifetime: 5184000              # Lifetime of the trusted device token
        extend_lifetime: false         # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax", "strict" or null

    email:
        digits: 6
        enabled: true
        sender_email: test@test.com
        mailer: App\Service\MailService
        template: medecin/security/2fa.html.twig
```

Also my MedLoginFormAuthenticator class. What's important in there is the onAuthenticationSuccess function where I had to change the redirect route to make it works
```

/**
 * Class MedLoginFormAuthenticator
 * @package App\Security\Customer\Medecin
 */
class MedLoginFormAuthenticator extends AbstractFormLoginAuthenticator
{
    use TargetPathTrait;

    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    /**
     * @var FormFactoryInterface
     */
    private $factory;

    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @var SessionInterface
     */
    private $session;

    /**
     * MedLoginFormAuthenticator constructor.
     * @param EntityManagerInterface $entityManager
     * @param SessionInterface $session
     * @param ContainerInterface $container
     * @param RouterInterface $router
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @param FormFactoryInterface $factory
     */
    public function __construct(EntityManagerInterface $entityManager, SessionInterface $session, ContainerInterface $container, RouterInterface $router, UserPasswordEncoderInterface $passwordEncoder, FormFactoryInterface $factory)
    {
        $this->router = $router;
        $this->passwordEncoder = $passwordEncoder;
        $this->factory = $factory;
        $this->container = $container;
        $this->entityManager = $entityManager;
        $this->session = $session;
    }

    /**
     * @param Request $request
     * @return bool
     */
    public function supports(Request $request)
    {
        return 'medecin_login' === $request->attributes->get('_route')
            && $request->isMethod('POST');
    }

    /**
     * @param Request $request
     * @return array|mixed
     */
    public function getCredentials(Request $request)
    {

        // Création du formulaire de connexion
        $form = $this->factory->create(LoginMedFormType::class);

        // Injection de la requête
        $form->handleRequest($request);

        // Vérification tous les champs sont présent ainsi que le jeton cfrs
        if ($form->isSubmitted() && $form->isValid()) {

            $credentials = [
                'email' => $form->get("username")->getData(),
                'password' => $form->get("password")->getData(),
            ];

            // Vérification du captcha si présent dans le formulaire
            if (isset($form['captchaCode'])) {

                // Récupération du captcha depuis le formulaire
                $credentials['captchaCode'] = $form->get('captchaCode')->getData();

                /** @var \Captcha $captcha */
                // Récupération de l'instance de vérification du captcha
                $captcha = $this->container->get('simple_captcha')->getInstance('LoginCaptcha');

                // Validation du captcha
                $isHuman = $captcha->Validate($credentials['captchaCode']);

                if (!$isHuman) {
                    throw new InvalidCaptchaException("captcha invalid");
                }
            }

            $request->getSession()->set(
                Security::LAST_USERNAME,
                $credentials['email']
            );

            return $credentials;
        }

        return [];
    }

    /**
     * @param mixed $credentials
     * @param UserProviderInterface $userProvider
     * @return User|mixed|UserInterface|null
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        /** @var User $user */
        try {
            $user = $this->entityManager->getRepository(User::class)->loadUserByUsername($credentials['email']);
        } catch (\Exception $e) {
            throw new BadCredentialsException();
        }

        if (!$user) {
            throw new BadCredentialsException();
        }

        // Si un utilisateur est trouvé récupération de son score de connexion échoué
        $this->session->set('LOGIN_ATTEMPTS', $user->getLoginAttempts());

        return $user;
    }

    /**
     * @param mixed $credentials
     * @param UserInterface $user
     * @return bool
     */
    public function checkCredentials($credentials, UserInterface $user)
    {
        return $this->passwordEncoder->isPasswordValid($user, $credentials['password']);
    }

    /**
     * @param Request $request
     * @param TokenInterface $token
     * @param string $providerKey
     * @return RedirectResponse|\Symfony\Component\HttpFoundation\Response|null
     */
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse($this->router->generate('2fa_login'));
    }

    /**
     * @return string
     */
    protected function getLoginUrl()
    {
        return $this->router->generate('medecin_login');
    }
}
```
If you can help me by any way, it would be so much appreciable !

**Comment by LucasSouriau** [comment] 2019-05-10 12:39
![Capture d’écran 2019-05-10 à 14 39 25](https://user-images.githubusercontent.com/9657688/57528016-6fee7100-7331-11e9-9bc7-bb1bc9e7b7e4.png)

**Comment by scheb** [comment] 2019-05-11 10:20
Which bundle and Symfony version are you using?

Your firewall path configuration
`pattern: ^/(login|m|support|retailer|telesphore|admin|easyadmin)`
must include include the path of the `2fa_login` and `2fa_login_check` routes. But this not the problem with the authentication code not being sent & persisted.

So let's debug that. The TwoFactorToken says that the `email` provider has been started. Please check if the method
- bundle version 3: `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\EmailTwoFactorProvider::beginAuthentication()`
- bundle version 4: `Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Email\EmailTwoFactorProvider::prepareAuthentication()`

is executed on login.

**Comment by LucasSouriau** [comment] 2019-05-12 20:47
I'm using Symfony 4 and the version 4 of the bundle

Thanks bout the pattern! I've set it now

Apparently the prepareAuthentication method isn't even called. It also seems like I still got the IS_AUTHENTICATED_ANONYMOUSLY attribute when I access the /2fa form page... I don't know if it's actually normal

**Comment by scheb** [comment] 2019-05-13 08:25
Could you please check again with the path pattern fixed. The more I think about it, could be in fact related.

**Comment by LucasSouriau** [comment] 2019-05-13 09:31
Not even with the pattern fixed
The onTwoFactorAuthenticationRequest is also not executed

**Comment by LucasSouriau** [comment] 2019-05-13 14:59
When do the require event is actually supposed to be dispatch?

**Comment by scheb** [comment] 2019-05-13 18:24
I may have found it. In 4.x the preparation method is only called, when the bundle force-redirects to the 2fa form. Since you're already redirecting to that page in your `onAuthenticationSuccess` method, this code path is never executed. That's a flaw in the implementation that I need to rework (but don't know yet how to do it best).

You have two options to work around this issue:
- Downgrade to bundle version 3.x
- Instead of redirecting to the 2fa page, redirect to a page that requires a fully authenticated user. That page will then redirect to the 2fa page and trigger the preparation step.

**Comment by LucasSouriau** [comment] 2019-05-13 19:04
Ok I think I get it! I've tried the second solution, but as I don't have the IS_AUTHENTICATED_2FA_IN_PROGRESS it keeps redirecting me to login, then the page that needs a fully authenticated user, and again and again and again.
And also cause I got that condition at the top of the loginAction method
```
if ($this->getUser() !== null) {
            return $this->redirectToRoute('fully_auth');
        }
```

**Comment by LucasSouriau** [comment] 2019-05-14 07:53
In fact that code section is always executed in the TwoFactorListener class, btw the return statement doesn't allow me to execute the next condition which is supposed to send the mail

```
        if ($this->twoFactorAccessDecider->isAccessible($request, $currentToken)) {
            return;
        }
```

**Comment by scheb** [comment] 2019-05-14 19:33
Downgrade to 3.x and wait until the issue is fixed in 4.x. That's definitely the better solution for you. Otherwise i believe, with your setup, there is no guarantee that the preparation step is executed.

I can't see your `access_control` configuration up there, so please make sure you have it configured as seen here: https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/installation.md#step-4-configure-the-firewall

Some additional information, since you asked:

```php
        if ($this->getUser() !== null) {
            return $this->redirectToRoute('fully_auth');
        }
```
^ This is fine, shouldn't be an issue. The `fully_auth` route may redirect to the 2fa form when you're in the "IS_AUTHENTICATED_2FA_IN_PROGRESS" state, but that's what its supposed to do.

```
        if ($this->twoFactorAccessDecider->isAccessible($request, $currentToken)) {
            return;
        }
```
^ This statement should only be true when the authentication form is shown or you have the path defined to be accessible to anonymous users in `access_control`. So it let's the user pass and will apply access rules from `access_control`. This is intended behavior.

**Comment by scheb** [comment] 2019-06-25 19:38
Closing this issue. #212 is there to solve it.

**Closed by scheb** 2019-06-25 19:38 UTC
Labels: Support
