### ISSUE TITLE
Email never sent when not preferred provider.

### ISSUE THREAD

**Issue by RomainL972** [scheb/two-factor-bundle#214] opened 2019-06-03 01:52 UTC
**Bundle version**: 4.1.0
**Symfony version**: 4.2.9

**Description**

If the email provider isn't the preferred one, the mail will never be sent even after going to "/2fa?preferProvider=email".

**To Reproduce**
1. Enable email provider plus another one
2. implement PreferredProviderInterface and choose the other provider as preferred for your user
3. Begin to login
4. When the 2fa form shows, change the provider for email (go to /2fa?preferProvider=email)
5. No mail is sent (I waited a very long time) and the debug toolbar confirms it

**Comment by scheb** [comment] 2019-06-03 08:41
You're most likely running into #212. I'd recommend downgrading to bundle version 3.x until the issue is fixed.

**Comment by scheb** [comment] 2019-06-25 19:39
Closing this issue. #212 is there to solve it.

**Closed by scheb** 2019-06-25 19:39 UTC
Labels: Support
